---
title: "Roster_compile_checks"
author: "Sarah"
date: "10/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Libraries
```{r}
library(lubridate)
library(tidyverse)
library(readxl)
library(openxlsx)
library(fs)
library(here)
library(kableExtra)

```

# Read in files that were sent to WDRS to roster
```{r}
# Creates list of all compiled_roster files in these folders
# June 1,2021 through September 29, 2021

compile_files <- dir_ls(here("write_roster_here\\Archive"), recurse = TRUE, type = "any", regexp = "2021-[0][0,6-9]-[0-9][0-9]/Compiled")

# read files in with all columns as character
if(length(compile_files > 0)){

 roster_files <- dput(as.vector(compile_files))
 names(roster_files) <- roster_files


  Compile_Rosters <- roster_files %>%
    map_dfr(~read_csv(., col_types = cols(
      CASE_ID = col_character(),
      SEQUENCE_SGTF = col_character(),
      SEQUENCE_SPECIMEN = col_character(),
      SEQUENCE_REASON = col_character(),
      SEQUENCE_DATE = col_character(),
      SEQUENCE_LAB = col_character(),
      SEQUENCE_STATUS = col_character(),
      SEQUENCE_REPOSITORY = col_character(),
      SEQUENCE_ACCESSION = col_character(),
      SEQUENCE_VARIANT = col_character(),
      SEQUENCE_CLINICAL_ACCESSION = col_character(),
      SEQUENCE_SPECIMEN_COLLECTION_DATE = col_character(),
      SEQUENCE_NOTES = col_character(),
      SEQUENCE_REVIEWED = col_character(),
      Case.Note = col_character()
    )), .id = "index")

}

# remove white space from collection date
Compiled_Roster <- bind_rows(Compile_Rosters) %>% mutate(SEQUENCE_SPECIMEN_COLLECTION_DATE =
                                                           str_trim(SEQUENCE_SPECIMEN_COLLECTION_DATE, side = "both"))

```


# Make table by lab with counts by SEQUENCE_REASON, total number per lab, and percent missing SEQUENCE_REASON
```{r}

seq_reason_table <-
Compiled_Rosterjunesept  %>% 
   count(SEQUENCE_REASON, SEQUENCE_LAB) %>% 
  group_by(SEQUENCE_LAB) %>% 
   mutate(lab_total = sum(n),
     percent_reason = scales::percent(n/sum(n))) %>% 
  select(SEQUENCE_LAB, SEQUENCE_REASON, n, lab_total, percent_reason) %>% 
  arrange(SEQUENCE_LAB)


```

# View as a table, with updated column names
```{r}
knitr::kable(
  seq_reason_table, 
  col.names = c('SEQUENCE_LAB', 'SEQUENCE_REASON', 'Count', 'Total Number in Roster', 'Percent of Responses'),
  caption = "Sequence Reason by Lab (June-Sept)")
```

Save table as html
```{r}
table <- kbl(
  seq_reason_table, 
  col.names = c('SEQUENCE_LAB', 'SEQUENCE_REASON', 'Count', 'Total Number in Roster', 'Percent of Responses'),
  caption = "Sequence Reason by Lab (June-Sept)") %>% 
  kable_styling(bootstrap_options = "striped")

write_file(table, paste0(here("Investigations\\", "Sequence_Reason_table.html")))



```



# Make table by lab with counts of missing SEQUENCE_REASON, total number per lab, and percent missing SEQUENCE_REASON
```{r}


seq_reason_table_na_only <-
Compiled_Roster %>% 
    group_by(SEQUENCE_LAB) %>% 
    mutate(is_missing = sum(is.na(SEQUENCE_REASON)), lab_total = length(SEQUENCE_REASON), 
           percent_missing = scales::percent(is_missing/lab_total)
    ) %>% 
    filter(is.na(SEQUENCE_REASON)) %>% select(SEQUENCE_LAB, SEQUENCE_REASON, is_missing, lab_total, percent_missing) %>% distinct() %>% arrange(SEQUENCE_LAB)

# Save table 
table_na_only <- kbl(
  seq_reason_table_na_only, 
  col.names = c('SEQUENCE_LAB', 'SEQUENCE_REASON', 'Number Missing', 'Total Number in Roster', 'Percent of Responses'),
  caption = "Missing Sequence Reason by Lab (June-Sept)") %>% 
  kable_styling(bootstrap_options = "striped")

write_file(table_na_only, paste0(here("Investigations\\", "Missing_Sequence_Reason_table.html")))

```

